name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test2
          POSTGRES_USER: test2
          POSTGRES_PASSWORD: test2
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests with production environment variable
        run: |
          export production=test2
          export DATABASE_URL="postgresql://test:test@localhost:5432"
          poetry run pytest
