name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          #POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
    
    env: 
        SQLALCHEMY_DATABASE_URI: postgresql://postgres:test@localhost:5432/test

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends postgresql-client
      - name: Insert test database tables
        run: |
          psql -d $SQLALCHEMY_DATABASE_URI < src/schema.sql 
      - name: Run tests with production environment variable
        run: |
          poetry run pytest
