name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Create table
        env:
          PGPASSWORD: test
        run: |
          psql -h localhost -U test -d test -a -f src/delschema.sql
          psql -h localhost -U test -d test -a -f src/schema.sql
      - name: Run tests with production environment variable
        run: |
          export production=test
          export DATABASE_URL="postgresql://test:test@localhost:5432"
          poetry run pytest

      - name: Pylint
        run: | 
          poetry run pylint src


      - name: Setup chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Configure chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Run robot tests
        run: bash run_robot_tests.sh

